### ISSUE TITLE
[BUG] changing the viewbox size doesn't seem to expand the code to fit.

### ISSUE THREAD

**Issue by fr3nch13** [chillerlan/php-qrcode#222] opened 2023-10-24 19:33 UTC
Tested on 4.3, 5.0-beta, and main.

**Describe the bug or unexpected behaviour**

setting the `svgViewBoxSize` to an int, doesn't seem to fill the viewBox with the QrCode.
Without setting the `svgViewBoxSize`, the output makes it `<svg xmlns="http://www.w3.org/2000/svg" class="qr-svg qrcode" viewBox="0 0 41 41" preserveAspectRatio="xMidYMid">`.
Setting it, and the only thing that changes is the `viewBox="0 0 500 500"`

Unfortunately I don't know enough about SVG to know if this is the intended output change, or if there should be more.

Hopefully I'm just overlooking some setting that I should be using.

**Steps to reproduce the behavior**

Current code, simplified for testing.

```php
    $this->options = new QROptions([
            'svgViewBoxSize' => $this->getConfig('svgViewBoxSize', 500),
            'eccLevel' => $this->getConfig('eccLevel', EccLevel::H),
            'outputType' => $this->getConfig('outputType', QROutputInterface::MARKUP_SVG),
            'svgUseFillAttributes' => $this->getConfig('svgUseFillAttributes', true),
            'drawLightModules' => $this->getConfig('drawLightModules', false),
    ]);
$this->data = "https://localhost";
$optionsLight = clone $this->options;
//$optionsLight->setColor($color);
$qrLight = new ChillerlanQRCode($optionsLight);
$qrLight->render($this->data, $qrImagePathLight);
```

**Expected behavior**

That if I set the viewBox size, that the QR code,  (and svg logo inside) would expand to fill the view box.

**Screenshots**
[SVG Gist](https://gist.github.com/fr3nch13/ceaf37612c7f2c8fe2a6ee7c6154866d)

![1-dark](https://github.com/chillerlan/php-qrcode/assets/7828/177a55c6-b608-4250-9c42-6e5d993967fe)

**Environment (please complete the following information):**

- PHP version/OS: 8.2
- Library version: 4.3, 5.0-beta, dev-main

**Additional context**

**Comment by codemasher** [comment] 2023-10-24 20:15
Hi. This is not a bug. The expectation that changing the `viewbox` attribute also changes the fill size of the content is a misconception. The [SVG documentation says](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox):

> The viewBox attribute defines the position and dimension, in user space, of an SVG viewport.

It's useful to change this attribute if you want to add additional content, e.g. text under the QR symbol. The setting `$svgViewBoxSize` is deprecated because of this and the preferred method is to override the method `QRMarkupSVG::header()`.

https://github.com/chillerlan/php-qrcode/blob/8c0da25c72e2b2f2303ce460a7a7193555cc7c52/src/Output/QRMarkupSVG.php#L90-L110

In order to change the size of the SVG to a fixed, which is what i assume you expect, you need to either add `width` and `height` attributes to the `svg` root element or change its size via CSS.

**Comment by codemasher** [comment] 2023-10-24 20:25
In fact, i should remove this option entirely before releasing v5. I added it a long time ago when i knew nothing about SVG and fell for the same misconception. It is misleading and most likely not widely used anyway.

**Comment by codemasher** [comment] 2023-10-24 20:48
I was experimenting in the past but there's no "best" way to set the size for the SVG, so i decided to leave this to the user entirely. the `$scale` option in combination with the `width` and `height` attributes isn't the best as it would fix the size which is often not preferred ([ImagMagick requires them](https://github.com/chillerlan/php-qrcode/blob/main/examples/imagickConvertSVGtoPNG.php#L33-L42) for properly sized output, though). SVG output is almost exclusively used in a web browser where CSS is available, and if it isn't, the size can be changed via CSS in the `<defs>` element or the aforementioned attributes.

**Comment by fr3nch13** [comment] 2023-10-24 20:53
Sigh, yeah. The whole point of the "S" in SVG. The issue I'm coming across, specific to me. I'm trying to import the QR codes, and the viewport is 0 0 41 41. which gimp makes a 41x41 pixel import. I can scale it up when importing, but it then becomes really fuzzy, like trying to upscale a jpg/png/etc. I was just trying to solve this from an import perspective.

**Comment by codemasher** [comment] 2023-10-24 20:54
That sounds like the same issue i had when converting via ImageMagick - try the output from that example and see what happens.

**Comment by fr3nch13** [comment] 2023-10-24 21:00
Ok, I just pulled/composer update and I'm running on dev-main.

I copy-pasta'd your svg example here: 
https://github.com/chillerlan/php-qrcode/blob/main/examples/svg.php

and getting a viewport of 53 and it's trying to import as a 53x53 image:
```
<svg xmlns="http://www.w3.org/2000/svg" class="qr-svg qrcode" viewBox="0 0 53 53" preserveAspectRatio="xMidYMid">
```

**Comment by codemasher** [comment] 2023-10-24 21:03
That is correct. I meant try the output from [the imagick conversion example](https://github.com/chillerlan/php-qrcode/blob/57448af264a4bc0aca85a9ce61769aa6240b9481/examples/imagickConvertSVGtoPNG.php#L33-L42) with the changed `<svg>` element.

**Comment by codemasher** [comment] 2023-10-24 21:04
I'm going to close this issue here. Feel free to open [a discussion](https://github.com/chillerlan/php-qrcode/discussions) for further questions.

**Closed by codemasher** 2023-10-24 21:04 UTC

**Comment by codemasher** [comment] 2023-10-24 21:05
> I could be wrong, but it'd be nice to have the svg be large by default, for importing into things like gimp/photoshop/cad/non-html, browser. Then make them scale it down with css/html attributes.

Like i said, that is not the main focus or use case for SVG and the reason why i decided not to add these attributes.

**Comment by fr3nch13** [comment] 2023-10-24 21:05
Oh, derp.

I got: `<svg xmlns="http://www.w3.org/2000/svg" class="qr-svg qrcode" viewBox="0 0 41 41" preserveAspectRatio="xMidYMid" width="205" height="205">`

**Comment by fr3nch13** [comment] 2023-10-24 21:07
> > I could be wrong, but it'd be nice to have the svg be large by default, for importing into things like gimp/photoshop/cad/non-html, browser. Then make them scale it down with css/html attributes.
> 
> Like i said, that is not the main focus or use case for SVG and the reason why i decided not to add these attributes.

Gotcha, well at least you made it extendable, and you did a great job on the documentation, I personally appreciate that part! :-p

**Comment by codemasher** [comment] 2023-10-24 21:08
Glad to hear because that's exactly why i'm doing this.

**Comment by fr3nch13** [comment] 2023-10-24 21:12
Well I don't mind being your userland guinea pig. 

I'm using it over here, in case you're curious: https://qr.fr3nch.com

**Comment by fr3nch13** [comment] 2023-10-24 21:14
I chose yours, because it's much more configurable, and it runs locally, verse google's graph api. 

I also wasn't going to pay bitly and other QR code hosters $35/month when I can make my own site.

**Comment by codemasher** [comment] 2023-10-24 21:23
Ah yes the QR code scammers. Still a wild concept to me so generate a QR code and charge for it on a monthly basis - for tracking statistics you can get for free elsewhere. If i had the time and capacity i'd run such a website for free haha. [Oh wait, i did (cheaply)](https://smiley.codes/qrcode/)
